### ISSUE TITLE
Following is showing up in frontend

### ISSUE THREAD

**Issue by creative-codes** [hojaonline/pits_downloadcenter#10]
![screen shot 2017-10-30 at 08 38 00](https://user-images.githubusercontent.com/33216662/32159477-01fbd998-bd4e-11e7-855d-e43987753bb7.png)

I am not shure why that is so? Maybe you can help me.

The newest version is running (1.1.0) and and it is typo3 6.2.30

And that is in install tool:
![screen shot 2017-10-30 at 08 41 56](https://user-images.githubusercontent.com/33216662/32159526-380d1ef2-bd4e-11e7-9a7f-cf2f5cce736f.png)

**Comment by hojaonline** [comment]
It seems like javascript error. Please refer the documentation for integrating the plugin. Run the DB Analyser tasks and clear the caches. Also check the network console for any JS errors.
