### ISSUE TITLE
TYPO3 v8 LTS (8.7) compatibility

### ISSUE THREAD

**Issue by webdev2027** [hojaonline/pits_downloadcenter#11]
Great extension - thanks! The compatibility to TYPO3 8.7 LTS will be great!

` No columns definition in TCA table tx_pitsdownloadcenter_domain_model_filetype (More information)
UnexpectedValueException thrown in file /html/typo3/typo3_src-8.7.9/typo3/sysext/backend/Classes/Form/FormDataProvider/InitializeProcessedTca.php in line 48.`

**Comment by hojaonline** [comment]
@webdev2027 The version 2.0.0 exclusive for TYPO3 8LTS is under development and it will be released before the first week of March 2018.
