### ISSUE TITLE
Semantical Error

### ISSUE THREAD

**Issue by Hobokens** [hojaonline/pits_downloadcenter#20]
Hi,
I try to install pits_downloadcenter with TYPO3 9.5.4 and get the following error:
```
Oops, an error occurred!
[Semantical Error] The annotation "@void" in method PITS\PitsDownloadcenter\Controller\DownloadController::forceDownloadAction() was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

Regards
Hobokens

**Comment by hojaonline** [comment]
Dear @Hobokens 
This issue is fixed in the master branch please check

**Comment by Hobokens** [comment]
Dear @hojaonline ,
thanks a lot for the fix. Everything is perfect now.
