### ISSUE TITLE
Problems after installation of TYPO3 extension pits_downloadcenter

### ISSUE THREAD

**Issue by Polameiro** [hojaonline/pits_downloadcenter#22]
I'm using TYPO3 9.5.5 and have installed pits_downloadcenter 3.0.1 extension.
I am encountering errors after installation in 'Extensions Manager'.

    Call to a member function admin_get_tables() on null" in "typo3conf/ext/pits_downloadcenter/class.ext_update.php line 68"

It seems that the extension pits_downloadcenter still relies on the deprecated database functionality.
I installed the extension "[TYPO3_DB compatibility layer for TYPO3 v9.x](https://extensions.typo3.org/extension/typo3db_legacy/)"  and everything went well. 

Regards,
Jos

**Comment by hojaonline** [comment]
Dear @Polameiro 
I removed the update layer from the extension. In the next release it will be fixed. you can choose the master branch for fixed version

**Comment by Polameiro** [comment]
Hello,

Sorry to bother you, but we have a project to launch and we bet on this
extension to show files and we couldn't get around this problem.

In version 2 it was possible to select which categories to show by creating
them on different nodes.
In version 3, I realized it would be through file storage. But it does not
work.  All categories created (even if they are empty) are listed in the
frontend!
Do you understand why? Can you help us?

Thanks

Jose Fernandes
