### ISSUE TITLE
pits downloadcenter not shown in IE11

### ISSUE THREAD

**Issue by fxp66** [hojaonline/pits_downloadcenter#24]
The List view is not shown in IE 11, every other Brwoser works well.
Is this an security issue of IE?

thanks for answer fxp

**Comment by fxp66** [comment]
... this error is thrown:

> Can't execute code from a freed script

**Comment by hojaonline** [comment]
Dear @fxp66 
This is because I forgot to enable the polyfill support for the IE browser

**Comment by hojaonline** [comment]
@fxp66 it will be fixed in the next release.
